// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Counter struct {
	ID    int64
	Value int64
}

type Url struct {
	ID        int64
	ShortCode string
	LongUrl   string
	CreatedAt int64
}

type UrlStat struct {
	ShortCode   string
	FollowCount int64
	FirstFollow sql.NullInt64
	LastFollow  sql.NullInt64
}
