// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const countURLs = `-- name: CountURLs :one
SELECT COUNT(*) AS total FROM urls
`

func (q *Queries) CountURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countURLs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls WHERE short_code = ?
`

func (q *Queries) DeleteURL(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, deleteURL, shortCode)
	return err
}

const deleteURLStats = `-- name: DeleteURLStats :exec
DELETE FROM url_stats WHERE short_code = ?
`

func (q *Queries) DeleteURLStats(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, deleteURLStats, shortCode)
	return err
}

const getCounter = `-- name: GetCounter :one
SELECT id, value FROM counter WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (Counter, error) {
	row := q.db.QueryRowContext(ctx, getCounter)
	var i Counter
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const getFollowStats = `-- name: GetFollowStats :one
SELECT short_code, follow_count, first_follow, last_follow
FROM url_stats
WHERE short_code = ?
`

func (q *Queries) GetFollowStats(ctx context.Context, shortCode string) (UrlStat, error) {
	row := q.db.QueryRowContext(ctx, getFollowStats, shortCode)
	var i UrlStat
	err := row.Scan(
		&i.ShortCode,
		&i.FollowCount,
		&i.FirstFollow,
		&i.LastFollow,
	)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, long_url, created_at
FROM urls
WHERE short_code = ?
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertURL = `-- name: InsertURL :one
INSERT INTO urls (short_code, long_url)
VALUES (?, ?)
RETURNING id, short_code, long_url, created_at
`

type InsertURLParams struct {
	ShortCode string
	LongUrl   string
}

func (q *Queries) InsertURL(ctx context.Context, arg InsertURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, insertURL, arg.ShortCode, arg.LongUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listURLs = `-- name: ListURLs :many
SELECT id, short_code, long_url, created_at
FROM urls
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListURLsParams struct {
	ID    int64
	Limit int64
}

// Cursor-based pagination: pass last seen id (0 for first page).
func (q *Queries) ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.LongUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsWithStats = `-- name: ListURLsWithStats :many
SELECT
    u.id,
    u.short_code,
    u.long_url,
    u.created_at,
    COALESCE(s.follow_count, 0) AS follow_count,
    s.first_follow,
    s.last_follow
FROM urls u
LEFT JOIN url_stats s ON s.short_code = u.short_code
WHERE u.id > ?
ORDER BY u.id ASC
LIMIT ?
`

type ListURLsWithStatsParams struct {
	ID    int64
	Limit int64
}

type ListURLsWithStatsRow struct {
	ID          int64
	ShortCode   string
	LongUrl     string
	CreatedAt   int64
	FollowCount int64
	FirstFollow sql.NullInt64
	LastFollow  sql.NullInt64
}

func (q *Queries) ListURLsWithStats(ctx context.Context, arg ListURLsWithStatsParams) ([]ListURLsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listURLsWithStats, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListURLsWithStatsRow{}
	for rows.Next() {
		var i ListURLsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.LongUrl,
			&i.CreatedAt,
			&i.FollowCount,
			&i.FirstFollow,
			&i.LastFollow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCounter = `-- name: SetCounter :exec
INSERT INTO counter (id, value) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetCounter(ctx context.Context, value int64) error {
	_, err := q.db.ExecContext(ctx, setCounter, value)
	return err
}

const upsertFollowStats = `-- name: UpsertFollowStats :exec
INSERT INTO url_stats (short_code, follow_count, first_follow, last_follow)
VALUES (?, 1, ?, ?)
ON CONFLICT(short_code) DO UPDATE SET
    follow_count = url_stats.follow_count + 1,
    last_follow  = excluded.last_follow,
    first_follow = COALESCE(url_stats.first_follow, excluded.first_follow)
`

type UpsertFollowStatsParams struct {
	ShortCode   string
	FirstFollow sql.NullInt64
	LastFollow  sql.NullInt64
}

func (q *Queries) UpsertFollowStats(ctx context.Context, arg UpsertFollowStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertFollowStats, arg.ShortCode, arg.FirstFollow, arg.LastFollow)
	return err
}
